// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvpRkNln-VhS9mZ5orkeX5y2MaHsa8VmU',
    appId: '1:388149789363:web:1e15b33cb426b446cba6c6',
    messagingSenderId: '388149789363',
    projectId: 'madrassa-da9ca',
    authDomain: 'madrassa-da9ca.firebaseapp.com',
    storageBucket: 'madrassa-da9ca.appspot.com',
    measurementId: 'G-GQW0CZMPFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZ9j1wLqtvWtMhTo-1o-INXKiyYgzKaE',
    appId: '1:388149789363:android:32e39837bacfe9f8cba6c6',
    messagingSenderId: '388149789363',
    projectId: 'madrassa-da9ca',
    storageBucket: 'madrassa-da9ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTNgsFJEDglPcl6NSMK48353ynDR_x68',
    appId: '1:388149789363:ios:f8390e340f84a141cba6c6',
    messagingSenderId: '388149789363',
    projectId: 'madrassa-da9ca',
    storageBucket: 'madrassa-da9ca.appspot.com',
    iosBundleId: 'com.example.madrassa',
  );
}
